spring:
  application:
    name: genidxpage
  datasource:
    url: jdbc:mysql://localhost:3306/genidxpage?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

webArchive:
  rootUri: x
  checkArchivedUri: /wayback/available?url={url}&timestamp={timestamp}
