spring:
  application:
    name: genidxpage
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=YEAR,MONTH
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console #url: localhost:8080/h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

web-archive:
  root-uri: https://archive.org
  check-archived-uri: /wayback/available?url={url}

bulk-request:
  input-path: static/year-month-list
index-page:
  path: /app/static

logging:
  file:
    name: log/app.log
  level:
    root: INFO
    org.mybatis: DEBUG
    com.mysql.cj.jdbc: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n"
